# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 192.168.99.5, 192.168.99.6
  become: yes

  tasks:

- name: Call Roles
  hosts: 192.168.99.5, 192.168.99.6
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
